-- ============================================
-- RE:ADVISOR - Full Database Schema
-- ============================================
-- 
-- This file contains the complete database schema for RE:Advisor.
-- Run this file in Supabase SQL Editor to set up the entire database.
--
-- Includes:
-- - Base schema (tables, triggers, RLS policies)
-- - All migrations (001-007, 20240601)
-- - Seed data (service types)
-- - Storage bucket configuration
--
-- Version: 1.0.0
-- Last Updated: 2025-12-01
-- ============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- CORE TABLES
-- ============================================

-- PROFILES
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name TEXT,
  last_name TEXT,
  title TEXT,
  email TEXT,
  phone TEXT,
  location TEXT,
  timezone TEXT,
  company TEXT,
  website TEXT,
  linkedin TEXT,
  twitter TEXT,
  bio TEXT,
  avatar_url TEXT,
  stripe_customer_id TEXT UNIQUE,
  joined_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completion_percentage INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  -- Onboarding fields (from migrations)
  is_first_login BOOLEAN DEFAULT TRUE,
  onboarding_progress INTEGER DEFAULT 0,
  onboarding_step INTEGER DEFAULT 1,
  onboarding_completed BOOLEAN DEFAULT FALSE,
  onboarding_skipped BOOLEAN DEFAULT FALSE,
  onboarding_completed_at TIMESTAMP WITH TIME ZONE,
  profile_status TEXT DEFAULT 'draft', -- 'draft', 'submitted', 'approved', 'rejected', 'revision_required'
  -- Stripe fields
  stripe_account_id TEXT,
  stripe_account_status TEXT DEFAULT 'not_started', -- 'not_started', 'initiated', 'pending', 'active', 'failed'
  -- KYC fields
  kyc_status TEXT DEFAULT 'not_started', -- 'not_started', 'pending', 'verified', 'failed'
  kyc_submitted_at TIMESTAMP WITH TIME ZONE,
  kyc_verified_at TIMESTAMP WITH TIME ZONE,
  -- Subscription fields
  subscription_plan TEXT DEFAULT 'free', -- 'free', 'starter', 'professional', 'enterprise'
  subscription_status TEXT DEFAULT 'inactive', -- 'inactive', 'active', 'cancelled', 'past_due'
  subscription_expires_at TIMESTAMP WITH TIME ZONE
);

-- FAMILIES
CREATE TABLE IF NOT EXISTS families (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  wealth TEXT,
  members_count INTEGER DEFAULT 0,
  role TEXT DEFAULT 'consultant', -- 'external-consul', 'consultant', 'personal-advisor'
  payment_status TEXT DEFAULT 'pending', -- 'paid', 'pending', 'no-invoices'
  status TEXT DEFAULT 'active', -- 'active', 'pending', 'inactive'
  last_contact TIMESTAMP WITH TIME ZONE,
  industry TEXT,
  location TEXT,
  email TEXT,
  phone TEXT,
  description TEXT,
  invite_code TEXT UNIQUE,
  invite_link_enabled BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- FAMILY MEMBERS
CREATE TABLE IF NOT EXISTS family_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  role TEXT,
  email TEXT,
  avatar TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- FAMILY INVITATIONS
CREATE TABLE IF NOT EXISTS family_invitations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE,
  invited_by UUID REFERENCES profiles(id),
  email TEXT NOT NULL,
  role TEXT DEFAULT 'member', -- 'consul', 'council', 'member'
  invite_code TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'pending', -- 'pending', 'accepted', 'expired', 'cancelled'
  message TEXT,
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() + INTERVAL '7 days'),
  accepted_at TIMESTAMP WITH TIME ZONE,
  accepted_by UUID REFERENCES profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- TASKS
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  due_date TIMESTAMP WITH TIME ZONE,
  priority TEXT DEFAULT 'medium', -- 'low', 'medium', 'high'
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- SERVICE TYPES
CREATE TABLE IF NOT EXISTS service_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  icon TEXT,
  category TEXT, -- 'financial', 'legal', 'family', 'business', 'personal'
  is_active BOOLEAN DEFAULT TRUE,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- SERVICES
CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  service_type_id BIGINT REFERENCES service_types(id),
  name TEXT NOT NULL,
  status TEXT DEFAULT 'Pending', -- 'Active', 'In Progress', 'Pending'
  progress INTEGER DEFAULT 0,
  price TEXT,
  rate DECIMAL(10, 2),
  rate_type TEXT DEFAULT 'hourly', -- 'hourly', 'fixed', 'retainer'
  is_published BOOLEAN DEFAULT FALSE,
  max_clients INTEGER,
  current_clients INTEGER DEFAULT 0,
  start_date TIMESTAMP WITH TIME ZONE,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CONSULTATIONS
CREATE TABLE IF NOT EXISTS consultations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  date DATE,
  time TEXT,
  status TEXT DEFAULT 'scheduled', -- 'scheduled', 'completed', 'cancelled'
  meeting_link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CONSULTATION MEMBERS
CREATE TABLE IF NOT EXISTS consultation_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consultation_id BIGINT REFERENCES consultations(id) ON DELETE CASCADE,
  family_member_id BIGINT REFERENCES family_members(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CREDENTIALS
CREATE TABLE IF NOT EXISTS credentials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  issuer TEXT,
  year TEXT,
  status TEXT DEFAULT 'pending',
  credential_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- EXPERTISE
CREATE TABLE IF NOT EXISTS expertise (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  area TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- NOTIFICATIONS
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT, -- 'message', 'alert', 'update', 'reminder'
  title TEXT NOT NULL,
  description TEXT,
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CONVERSATIONS
CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE,
  title TEXT,
  last_message TEXT,
  last_message_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  unread_count INTEGER DEFAULT 0,
  pinned BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- MESSAGES
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id UUID REFERENCES auth.users(id),
  sender_name TEXT,
  content TEXT NOT NULL,
  read BOOLEAN DEFAULT FALSE,
  is_own BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- TRANSACTIONS
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id),
  family_id BIGINT REFERENCES families(id),
  amount TEXT,
  status TEXT,
  date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  description TEXT,
  type TEXT, -- 'income', 'payout', 'fee', 'subscription'
  invoice_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PAYMENT METHODS
CREATE TABLE IF NOT EXISTS payment_methods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  type TEXT, -- 'card'
  brand TEXT,
  last4 TEXT,
  expiry TEXT,
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- BANK ACCOUNTS
CREATE TABLE IF NOT EXISTS bank_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  bank_name TEXT,
  account_type TEXT,
  last4 TEXT,
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- TEAM MEMBERS
CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT DEFAULT 'member', -- 'admin', 'member', 'viewer'
  status TEXT DEFAULT 'pending', -- 'active', 'pending', 'inactive'
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- SUBSCRIPTIONS
CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  plan_id TEXT NOT NULL, -- 'starter', 'professional', 'enterprise'
  status TEXT DEFAULT 'active', -- 'active', 'cancelled', 'past_due'
  current_period_start TIMESTAMP WITH TIME ZONE,
  current_period_end TIMESTAMP WITH TIME ZONE,
  stripe_subscription_id TEXT,
  stripe_customer_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ONBOARDING STEPS
CREATE TABLE IF NOT EXISTS onboarding_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  step_name TEXT NOT NULL, -- 'profile_basics', 'credentials', 'services', 'stripe_setup', 'availability'
  completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMP WITH TIME ZONE,
  data JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(advisor_id, step_name)
);

-- AVAILABILITY SETTINGS
CREATE TABLE IF NOT EXISTS availability_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE UNIQUE,
  timezone TEXT DEFAULT 'America/New_York',
  buffer_before_minutes INTEGER DEFAULT 15,
  buffer_after_minutes INTEGER DEFAULT 15,
  min_notice_hours INTEGER DEFAULT 24,
  max_advance_days INTEGER DEFAULT 60,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- WEEKLY SCHEDULE
CREATE TABLE IF NOT EXISTS weekly_schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  day_of_week INTEGER NOT NULL, -- 0 = Sunday, 6 = Saturday
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  is_available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(advisor_id, day_of_week, start_time)
);

-- BLOCKED DATES
CREATE TABLE IF NOT EXISTS blocked_dates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(advisor_id, date)
);

-- KNOWLEDGE RESOURCES
CREATE TABLE IF NOT EXISTS knowledge_resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  type TEXT NOT NULL DEFAULT 'document', -- 'document', 'article', 'video', 'podcast', 'template', 'guide', 'link', 'checklist', 'learning-path'
  category TEXT DEFAULT 'General',
  content TEXT,
  file_url TEXT,
  external_url TEXT,
  thumbnail_url TEXT,
  is_featured BOOLEAN DEFAULT FALSE,
  is_published BOOLEAN DEFAULT TRUE,
  view_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RESOURCE SHARES
CREATE TABLE IF NOT EXISTS resource_shares (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT REFERENCES knowledge_resources(id) ON DELETE CASCADE,
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE,
  shared_by UUID REFERENCES profiles(id),
  shared_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(resource_id, family_id)
);

-- LEARNING PATHS
CREATE TABLE IF NOT EXISTS learning_paths (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  difficulty TEXT DEFAULT 'beginner', -- 'beginner', 'intermediate', 'advanced'
  estimated_duration_minutes INTEGER,
  is_published BOOLEAN DEFAULT TRUE,
  thumbnail_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- LEARNING PATH STEPS
CREATE TABLE IF NOT EXISTS learning_path_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  learning_path_id BIGINT REFERENCES learning_paths(id) ON DELETE CASCADE,
  resource_id BIGINT REFERENCES knowledge_resources(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT,
  content TEXT,
  step_order INTEGER NOT NULL,
  estimated_duration_minutes INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- LEARNING PATH RESOURCES (Many-to-many link)
CREATE TABLE IF NOT EXISTS learning_path_resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  learning_path_id BIGINT REFERENCES learning_paths(id) ON DELETE CASCADE,
  resource_id BIGINT REFERENCES knowledge_resources(id) ON DELETE CASCADE,
  position INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(learning_path_id, resource_id)
);

-- CONSTITUTION TEMPLATES
CREATE TABLE IF NOT EXISTS constitution_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  is_default BOOLEAN DEFAULT FALSE,
  is_published BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CONSTITUTION SECTIONS
CREATE TABLE IF NOT EXISTS constitution_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT REFERENCES constitution_templates(id) ON DELETE CASCADE,
  section_number INTEGER NOT NULL,
  title TEXT NOT NULL,
  content TEXT,
  is_required BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- FAMILY CONSTITUTIONS
CREATE TABLE IF NOT EXISTS family_constitutions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE,
  advisor_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  template_id BIGINT REFERENCES constitution_templates(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  status TEXT DEFAULT 'draft', -- 'draft', 'review', 'approved', 'archived'
  version INTEGER DEFAULT 1,
  adopted_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PUSH SUBSCRIPTIONS
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh_key TEXT NOT NULL,
  auth_key TEXT NOT NULL,
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- NOTIFICATION PREFERENCES
CREATE TABLE IF NOT EXISTS notification_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  push_enabled BOOLEAN DEFAULT TRUE,
  push_messages BOOLEAN DEFAULT TRUE,
  push_consultations BOOLEAN DEFAULT TRUE,
  push_payments BOOLEAN DEFAULT TRUE,
  push_updates BOOLEAN DEFAULT TRUE,
  push_alerts BOOLEAN DEFAULT TRUE,
  email_enabled BOOLEAN DEFAULT TRUE,
  email_messages BOOLEAN DEFAULT TRUE,
  email_consultations BOOLEAN DEFAULT TRUE,
  email_payments BOOLEAN DEFAULT TRUE,
  email_weekly_digest BOOLEAN DEFAULT TRUE,
  quiet_hours_enabled BOOLEAN DEFAULT FALSE,
  quiet_hours_start TIME DEFAULT '22:00',
  quiet_hours_end TIME DEFAULT '08:00',
  timezone TEXT DEFAULT 'UTC',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS idx_profiles_stripe_account_id ON profiles(stripe_account_id);
CREATE INDEX IF NOT EXISTS idx_profiles_profile_status ON profiles(profile_status);
CREATE INDEX IF NOT EXISTS idx_profiles_kyc_status ON profiles(kyc_status);
CREATE INDEX IF NOT EXISTS idx_families_advisor_id ON families(advisor_id);
CREATE INDEX IF NOT EXISTS idx_families_invite_code ON families(invite_code);
CREATE INDEX IF NOT EXISTS idx_family_members_family_id ON family_members(family_id);
CREATE INDEX IF NOT EXISTS idx_family_invitations_family_id ON family_invitations(family_id);
CREATE INDEX IF NOT EXISTS idx_family_invitations_email ON family_invitations(email);
CREATE INDEX IF NOT EXISTS idx_family_invitations_invite_code ON family_invitations(invite_code);
CREATE INDEX IF NOT EXISTS idx_family_invitations_status ON family_invitations(status);
CREATE INDEX IF NOT EXISTS idx_tasks_advisor_id ON tasks(advisor_id);
CREATE INDEX IF NOT EXISTS idx_services_advisor_id ON services(advisor_id);
CREATE INDEX IF NOT EXISTS idx_services_service_type_id ON services(service_type_id);
CREATE INDEX IF NOT EXISTS idx_consultations_advisor_id ON consultations(advisor_id);
CREATE INDEX IF NOT EXISTS idx_conversations_family_id ON conversations(family_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_transactions_advisor_id ON transactions(advisor_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_steps_advisor_id ON onboarding_steps(advisor_id);
CREATE INDEX IF NOT EXISTS idx_weekly_schedule_advisor_id ON weekly_schedule(advisor_id);
CREATE INDEX IF NOT EXISTS idx_blocked_dates_advisor_date ON blocked_dates(advisor_id, date);
CREATE INDEX IF NOT EXISTS idx_knowledge_resources_advisor_id ON knowledge_resources(advisor_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_resources_type ON knowledge_resources(type);
CREATE INDEX IF NOT EXISTS idx_learning_paths_advisor_id ON learning_paths(advisor_id);
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_id ON push_subscriptions(user_id);

-- ============================================
-- FUNCTIONS
-- ============================================

-- Generate invite code
CREATE OR REPLACE FUNCTION generate_invite_code()
RETURNS TEXT AS $$
DECLARE
  chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result TEXT := '';
  i INTEGER;
BEGIN
  FOR i IN 1..8 LOOP
    result := result || substr(chars, floor(random() * length(chars) + 1)::int, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql;

-- Set family invite code on insert
CREATE OR REPLACE FUNCTION set_family_invite_code()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.invite_code IS NULL THEN
    NEW.invite_code := generate_invite_code();
    WHILE EXISTS (SELECT 1 FROM families WHERE invite_code = NEW.invite_code AND id != NEW.id) LOOP
      NEW.invite_code := generate_invite_code();
    END LOOP;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Update members count on insert
CREATE OR REPLACE FUNCTION update_members_count_on_insert()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE families 
  SET members_count = members_count + 1,
      updated_at = NOW()
  WHERE id = NEW.family_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Update members count on delete
CREATE OR REPLACE FUNCTION update_members_count_on_delete()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE families 
  SET members_count = GREATEST(0, members_count - 1),
      updated_at = NOW()
  WHERE id = OLD.family_id;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- Handle new user signup
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO profiles (id, email, first_name, last_name)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'first_name',
    NEW.raw_user_meta_data->>'last_name'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create default notification preferences
CREATE OR REPLACE FUNCTION create_default_notification_preferences()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO notification_preferences (user_id)
  VALUES (NEW.id)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Generic updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- TRIGGERS
-- ============================================

-- Family invite code trigger
DROP TRIGGER IF EXISTS trigger_set_family_invite_code ON families;
CREATE TRIGGER trigger_set_family_invite_code
BEFORE INSERT ON families
FOR EACH ROW EXECUTE FUNCTION set_family_invite_code();

-- Members count triggers
DROP TRIGGER IF EXISTS trigger_update_members_count_insert ON family_members;
CREATE TRIGGER trigger_update_members_count_insert
AFTER INSERT ON family_members
FOR EACH ROW EXECUTE FUNCTION update_members_count_on_insert();

DROP TRIGGER IF EXISTS trigger_update_members_count_delete ON family_members;
CREATE TRIGGER trigger_update_members_count_delete
AFTER DELETE ON family_members
FOR EACH ROW EXECUTE FUNCTION update_members_count_on_delete();

-- New user trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- Notification preferences trigger
DROP TRIGGER IF EXISTS trigger_create_notification_preferences ON auth.users;
CREATE TRIGGER trigger_create_notification_preferences
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION create_default_notification_preferences();

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

-- Enable RLS on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE families ENABLE ROW LEVEL SECURITY;
ALTER TABLE family_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE family_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE consultation_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE expertise ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE availability_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE blocked_dates ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE resource_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_paths ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_path_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_path_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE constitution_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE constitution_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE family_constitutions ENABLE ROW LEVEL SECURITY;
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;

-- ============================================
-- DROP EXISTING POLICIES (if any)
-- ============================================

-- Profiles
DROP POLICY IF EXISTS "Users can view their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON profiles;

-- Families
DROP POLICY IF EXISTS "Advisors can view their families" ON families;
DROP POLICY IF EXISTS "Advisors can insert families" ON families;
DROP POLICY IF EXISTS "Advisors can update their families" ON families;
DROP POLICY IF EXISTS "Advisors can delete their families" ON families;

-- Family members
DROP POLICY IF EXISTS "Advisors can view members" ON family_members;
DROP POLICY IF EXISTS "Advisors can insert members" ON family_members;
DROP POLICY IF EXISTS "Advisors can update members" ON family_members;
DROP POLICY IF EXISTS "Advisors can delete members" ON family_members;
DROP POLICY IF EXISTS "Advisors can view members of their families" ON family_members;
DROP POLICY IF EXISTS "Advisors can insert members to their families" ON family_members;
DROP POLICY IF EXISTS "Advisors can update members of their families" ON family_members;
DROP POLICY IF EXISTS "Advisors can delete members from their families" ON family_members;

-- Family invitations
DROP POLICY IF EXISTS "Advisors can view their invitations" ON family_invitations;
DROP POLICY IF EXISTS "Advisors can create invitations" ON family_invitations;
DROP POLICY IF EXISTS "Advisors can update invitations" ON family_invitations;
DROP POLICY IF EXISTS "Advisors can delete invitations" ON family_invitations;
DROP POLICY IF EXISTS "Anyone can view invitation by code" ON family_invitations;
DROP POLICY IF EXISTS "Advisors can view their family invitations" ON family_invitations;
DROP POLICY IF EXISTS "Advisors can create family invitations" ON family_invitations;
DROP POLICY IF EXISTS "Advisors can update their family invitations" ON family_invitations;
DROP POLICY IF EXISTS "Advisors can delete their family invitations" ON family_invitations;

-- Tasks
DROP POLICY IF EXISTS "Advisors can manage tasks" ON tasks;
DROP POLICY IF EXISTS "Advisors can view their tasks" ON tasks;
DROP POLICY IF EXISTS "Advisors can insert tasks" ON tasks;
DROP POLICY IF EXISTS "Advisors can update their tasks" ON tasks;
DROP POLICY IF EXISTS "Advisors can delete their tasks" ON tasks;

-- Service types
DROP POLICY IF EXISTS "Service types are viewable by everyone" ON service_types;

-- Services
DROP POLICY IF EXISTS "Advisors can manage services" ON services;
DROP POLICY IF EXISTS "Advisors can view their services" ON services;

-- Consultations
DROP POLICY IF EXISTS "Advisors can manage consultations" ON consultations;
DROP POLICY IF EXISTS "Advisors can view their consultations" ON consultations;

-- Consultation members
DROP POLICY IF EXISTS "Advisors can manage consultation members" ON consultation_members;
DROP POLICY IF EXISTS "Advisors can view consultation members" ON consultation_members;

-- Credentials
DROP POLICY IF EXISTS "Advisors can manage credentials" ON credentials;
DROP POLICY IF EXISTS "Advisors can manage their credentials" ON credentials;

-- Expertise
DROP POLICY IF EXISTS "Advisors can manage expertise" ON expertise;
DROP POLICY IF EXISTS "Advisors can manage their expertise" ON expertise;

-- Notifications
DROP POLICY IF EXISTS "Users can manage notifications" ON notifications;
DROP POLICY IF EXISTS "Users can view their notifications" ON notifications;
DROP POLICY IF EXISTS "Users can insert their notifications" ON notifications;
DROP POLICY IF EXISTS "Users can update their notifications" ON notifications;
DROP POLICY IF EXISTS "Users can delete their notifications" ON notifications;

-- Conversations
DROP POLICY IF EXISTS "Advisors can manage conversations" ON conversations;
DROP POLICY IF EXISTS "Advisors can view their conversations" ON conversations;

-- Messages
DROP POLICY IF EXISTS "Advisors can view messages" ON messages;
DROP POLICY IF EXISTS "Advisors can insert messages" ON messages;
DROP POLICY IF EXISTS "Advisors can update messages" ON messages;
DROP POLICY IF EXISTS "Advisors can view messages in their conversations" ON messages;

-- Transactions
DROP POLICY IF EXISTS "Advisors can view transactions" ON transactions;
DROP POLICY IF EXISTS "Advisors can insert transactions" ON transactions;
DROP POLICY IF EXISTS "Advisors can view their transactions" ON transactions;

-- Payment methods
DROP POLICY IF EXISTS "Advisors can manage payment methods" ON payment_methods;
DROP POLICY IF EXISTS "Advisors can manage their payment methods" ON payment_methods;

-- Bank accounts
DROP POLICY IF EXISTS "Advisors can manage bank accounts" ON bank_accounts;
DROP POLICY IF EXISTS "Advisors can manage their bank accounts" ON bank_accounts;

-- Team members
DROP POLICY IF EXISTS "Advisors can manage team" ON team_members;

-- Subscriptions
DROP POLICY IF EXISTS "Advisors can manage subscription" ON subscriptions;
DROP POLICY IF EXISTS "Advisors can view their subscription" ON subscriptions;

-- Onboarding steps
DROP POLICY IF EXISTS "Advisors can manage onboarding" ON onboarding_steps;
DROP POLICY IF EXISTS "Advisors can manage their onboarding steps" ON onboarding_steps;

-- Availability
DROP POLICY IF EXISTS "Advisors can manage availability" ON availability_settings;
DROP POLICY IF EXISTS "Advisors can manage their availability settings" ON availability_settings;
DROP POLICY IF EXISTS "Advisors can manage schedule" ON weekly_schedule;
DROP POLICY IF EXISTS "Advisors can manage their weekly schedule" ON weekly_schedule;
DROP POLICY IF EXISTS "Advisors can manage blocked dates" ON blocked_dates;
DROP POLICY IF EXISTS "Advisors can manage their blocked dates" ON blocked_dates;

-- Knowledge resources
DROP POLICY IF EXISTS "Advisors can manage resources" ON knowledge_resources;
DROP POLICY IF EXISTS "Advisors can view their resources" ON knowledge_resources;
DROP POLICY IF EXISTS "Advisors can insert their resources" ON knowledge_resources;
DROP POLICY IF EXISTS "Advisors can update their resources" ON knowledge_resources;
DROP POLICY IF EXISTS "Advisors can delete their resources" ON knowledge_resources;

-- Resource shares
DROP POLICY IF EXISTS "Advisors can manage shares" ON resource_shares;
DROP POLICY IF EXISTS "Advisors can view their shared resources" ON resource_shares;
DROP POLICY IF EXISTS "Advisors can share their resources" ON resource_shares;
DROP POLICY IF EXISTS "Advisors can unshare their resources" ON resource_shares;

-- Learning paths
DROP POLICY IF EXISTS "Advisors can manage learning paths" ON learning_paths;
DROP POLICY IF EXISTS "Advisors can manage path steps" ON learning_path_steps;
DROP POLICY IF EXISTS "Advisors can manage their learning path steps" ON learning_path_steps;
DROP POLICY IF EXISTS "Advisors can manage path resources" ON learning_path_resources;

-- Constitution
DROP POLICY IF EXISTS "Advisors can manage constitution templates" ON constitution_templates;
DROP POLICY IF EXISTS "Advisors can manage constitution sections" ON constitution_sections;
DROP POLICY IF EXISTS "Advisors can manage their constitution sections" ON constitution_sections;
DROP POLICY IF EXISTS "Advisors can manage family constitutions" ON family_constitutions;

-- Push subscriptions
DROP POLICY IF EXISTS "Users can manage push subscriptions" ON push_subscriptions;
DROP POLICY IF EXISTS "Users can view their push subscriptions" ON push_subscriptions;
DROP POLICY IF EXISTS "Users can insert their push subscriptions" ON push_subscriptions;
DROP POLICY IF EXISTS "Users can delete their push subscriptions" ON push_subscriptions;

-- Notification preferences
DROP POLICY IF EXISTS "Users can manage preferences" ON notification_preferences;
DROP POLICY IF EXISTS "Users can view their notification preferences" ON notification_preferences;
DROP POLICY IF EXISTS "Users can insert their notification preferences" ON notification_preferences;
DROP POLICY IF EXISTS "Users can update their notification preferences" ON notification_preferences;

-- ============================================
-- CREATE POLICIES
-- ============================================

-- Profiles policies
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Families policies
CREATE POLICY "Advisors can view their families" ON families FOR SELECT USING (auth.uid() = advisor_id);
CREATE POLICY "Advisors can insert families" ON families FOR INSERT WITH CHECK (auth.uid() = advisor_id);
CREATE POLICY "Advisors can update their families" ON families FOR UPDATE USING (auth.uid() = advisor_id);
CREATE POLICY "Advisors can delete their families" ON families FOR DELETE USING (auth.uid() = advisor_id);

-- Family members policies
CREATE POLICY "Advisors can view members" ON family_members FOR SELECT USING (
  EXISTS (SELECT 1 FROM families WHERE families.id = family_members.family_id AND families.advisor_id = auth.uid())
);
CREATE POLICY "Advisors can insert members" ON family_members FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM families WHERE families.id = family_members.family_id AND families.advisor_id = auth.uid())
);
CREATE POLICY "Advisors can update members" ON family_members FOR UPDATE USING (
  EXISTS (SELECT 1 FROM families WHERE families.id = family_members.family_id AND families.advisor_id = auth.uid())
);
CREATE POLICY "Advisors can delete members" ON family_members FOR DELETE USING (
  EXISTS (SELECT 1 FROM families WHERE families.id = family_members.family_id AND families.advisor_id = auth.uid())
);

-- Family invitations policies
CREATE POLICY "Advisors can view their invitations" ON family_invitations FOR SELECT USING (
  EXISTS (SELECT 1 FROM families WHERE families.id = family_invitations.family_id AND families.advisor_id = auth.uid())
);
CREATE POLICY "Advisors can create invitations" ON family_invitations FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM families WHERE families.id = family_invitations.family_id AND families.advisor_id = auth.uid())
);
CREATE POLICY "Advisors can update invitations" ON family_invitations FOR UPDATE USING (
  EXISTS (SELECT 1 FROM families WHERE families.id = family_invitations.family_id AND families.advisor_id = auth.uid())
);
CREATE POLICY "Advisors can delete invitations" ON family_invitations FOR DELETE USING (
  EXISTS (SELECT 1 FROM families WHERE families.id = family_invitations.family_id AND families.advisor_id = auth.uid())
);
CREATE POLICY "Anyone can view invitation by code" ON family_invitations FOR SELECT USING (true);

-- Tasks policies
CREATE POLICY "Advisors can manage tasks" ON tasks FOR ALL USING (auth.uid() = advisor_id);

-- Service types policies (public read)
CREATE POLICY "Service types are viewable by everyone" ON service_types FOR SELECT USING (true);

-- Services policies
CREATE POLICY "Advisors can manage services" ON services FOR ALL USING (auth.uid() = advisor_id);

-- Consultations policies
CREATE POLICY "Advisors can manage consultations" ON consultations FOR ALL USING (auth.uid() = advisor_id);

-- Consultation members policies
CREATE POLICY "Advisors can manage consultation members" ON consultation_members FOR ALL USING (
  EXISTS (SELECT 1 FROM consultations WHERE consultations.id = consultation_members.consultation_id AND consultations.advisor_id = auth.uid())
);

-- Credentials policies
CREATE POLICY "Advisors can manage credentials" ON credentials FOR ALL USING (auth.uid() = advisor_id);

-- Expertise policies
CREATE POLICY "Advisors can manage expertise" ON expertise FOR ALL USING (auth.uid() = advisor_id);

-- Notifications policies
CREATE POLICY "Users can manage notifications" ON notifications FOR ALL USING (auth.uid() = user_id);

-- Conversations policies
CREATE POLICY "Advisors can manage conversations" ON conversations FOR ALL USING (
  EXISTS (SELECT 1 FROM families WHERE families.id = conversations.family_id AND families.advisor_id = auth.uid())
);

-- Messages policies
CREATE POLICY "Advisors can view messages" ON messages FOR SELECT USING (
  EXISTS (SELECT 1 FROM conversations JOIN families ON families.id = conversations.family_id WHERE conversations.id = messages.conversation_id AND families.advisor_id = auth.uid())
);
CREATE POLICY "Advisors can insert messages" ON messages FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM conversations JOIN families ON families.id = conversations.family_id WHERE conversations.id = messages.conversation_id AND families.advisor_id = auth.uid())
);
CREATE POLICY "Advisors can update messages" ON messages FOR UPDATE USING (
  EXISTS (SELECT 1 FROM conversations JOIN families ON families.id = conversations.family_id WHERE conversations.id = messages.conversation_id AND families.advisor_id = auth.uid())
);

-- Transactions policies
CREATE POLICY "Advisors can view transactions" ON transactions FOR SELECT USING (auth.uid() = advisor_id);
CREATE POLICY "Advisors can insert transactions" ON transactions FOR INSERT WITH CHECK (auth.uid() = advisor_id);

-- Payment methods policies
CREATE POLICY "Advisors can manage payment methods" ON payment_methods FOR ALL USING (auth.uid() = advisor_id);

-- Bank accounts policies
CREATE POLICY "Advisors can manage bank accounts" ON bank_accounts FOR ALL USING (auth.uid() = advisor_id);

-- Team members policies
CREATE POLICY "Advisors can manage team" ON team_members FOR ALL USING (auth.uid() = advisor_id);

-- Subscriptions policies
CREATE POLICY "Advisors can manage subscription" ON subscriptions FOR ALL USING (auth.uid() = advisor_id);

-- Onboarding steps policies
CREATE POLICY "Advisors can manage onboarding" ON onboarding_steps FOR ALL USING (auth.uid() = advisor_id);

-- Availability policies
CREATE POLICY "Advisors can manage availability" ON availability_settings FOR ALL USING (auth.uid() = advisor_id);
CREATE POLICY "Advisors can manage schedule" ON weekly_schedule FOR ALL USING (auth.uid() = advisor_id);
CREATE POLICY "Advisors can manage blocked dates" ON blocked_dates FOR ALL USING (auth.uid() = advisor_id);

-- Knowledge resources policies
CREATE POLICY "Advisors can manage resources" ON knowledge_resources FOR ALL USING (auth.uid() = advisor_id);

-- Resource shares policies
CREATE POLICY "Advisors can manage shares" ON resource_shares FOR ALL USING (
  EXISTS (SELECT 1 FROM knowledge_resources WHERE id = resource_shares.resource_id AND advisor_id = auth.uid())
);

-- Learning paths policies
CREATE POLICY "Advisors can manage learning paths" ON learning_paths FOR ALL USING (auth.uid() = advisor_id);
CREATE POLICY "Advisors can manage path steps" ON learning_path_steps FOR ALL USING (
  EXISTS (SELECT 1 FROM learning_paths WHERE id = learning_path_steps.learning_path_id AND advisor_id = auth.uid())
);
CREATE POLICY "Advisors can manage path resources" ON learning_path_resources FOR ALL USING (
  EXISTS (SELECT 1 FROM learning_paths WHERE id = learning_path_resources.learning_path_id AND advisor_id = auth.uid())
);

-- Constitution policies
CREATE POLICY "Advisors can manage constitution templates" ON constitution_templates FOR ALL USING (auth.uid() = advisor_id);
CREATE POLICY "Advisors can manage constitution sections" ON constitution_sections FOR ALL USING (
  EXISTS (SELECT 1 FROM constitution_templates WHERE id = constitution_sections.template_id AND advisor_id = auth.uid())
);
CREATE POLICY "Advisors can manage family constitutions" ON family_constitutions FOR ALL USING (auth.uid() = advisor_id);

-- Push subscriptions policies
CREATE POLICY "Users can manage push subscriptions" ON push_subscriptions FOR ALL USING (auth.uid() = user_id);

-- Notification preferences policies
CREATE POLICY "Users can manage preferences" ON notification_preferences FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- REALTIME
-- ============================================

-- Enable Realtime for specific tables (ignore errors if already added)
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE messages;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE conversations;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

-- ============================================
-- SERVICE REQUESTS (MVP1)
-- ============================================

-- SERVICE REQUESTS - Main engagement record
CREATE TABLE IF NOT EXISTS service_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_number TEXT UNIQUE,
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE NOT NULL,
  consultant_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  original_service_id BIGINT REFERENCES services(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'pending_consultant' NOT NULL,
  family_notes TEXT,
  consultant_comment TEXT,
  decline_reason TEXT,
  original_amount DECIMAL(10, 2),
  additional_amount DECIMAL(10, 2) DEFAULT 0,
  total_amount DECIMAL(10, 2),
  estimated_timeline TEXT,
  stripe_payment_intent_id TEXT,
  stripe_invoice_id TEXT,
  booked_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  consultant_response_deadline TIMESTAMP WITH TIME ZONE DEFAULT (NOW() + INTERVAL '48 hours'),
  consultant_confirmed_at TIMESTAMP WITH TIME ZONE,
  family_approval_deadline TIMESTAMP WITH TIME ZONE,
  family_approved_at TIMESTAMP WITH TIME ZONE,
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  paid_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- SERVICE REQUEST ITEMS
CREATE TABLE IF NOT EXISTS service_request_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT REFERENCES service_requests(id) ON DELETE CASCADE NOT NULL,
  service_id BIGINT REFERENCES services(id) ON DELETE SET NULL,
  service_name TEXT NOT NULL,
  service_description TEXT,
  price_at_booking DECIMAL(10, 2) NOT NULL,
  is_original BOOLEAN DEFAULT FALSE,
  added_by TEXT DEFAULT 'family',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- SERVICE DELIVERABLES
CREATE TABLE IF NOT EXISTS service_deliverables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT REFERENCES service_requests(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  external_link TEXT NOT NULL,
  uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- FAMILY ADVISOR ASSOCIATIONS
CREATE TABLE IF NOT EXISTS family_advisor_associations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE NOT NULL,
  consultant_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  service_request_id BIGINT REFERENCES service_requests(id) ON DELETE SET NULL,
  permission_level TEXT DEFAULT 'view' NOT NULL,
  modules JSONB DEFAULT '[]'::jsonb,
  status TEXT DEFAULT 'active' NOT NULL,
  granted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  revoked_at TIMESTAMP WITH TIME ZONE,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(family_id, consultant_id, service_request_id)
);

-- Indexes for service requests
CREATE INDEX IF NOT EXISTS idx_service_requests_family_id ON service_requests(family_id);
CREATE INDEX IF NOT EXISTS idx_service_requests_consultant_id ON service_requests(consultant_id);
CREATE INDEX IF NOT EXISTS idx_service_requests_status ON service_requests(status);
CREATE INDEX IF NOT EXISTS idx_service_request_items_request_id ON service_request_items(service_request_id);
CREATE INDEX IF NOT EXISTS idx_service_deliverables_request_id ON service_deliverables(service_request_id);
CREATE INDEX IF NOT EXISTS idx_family_advisor_associations_family ON family_advisor_associations(family_id);
CREATE INDEX IF NOT EXISTS idx_family_advisor_associations_consultant ON family_advisor_associations(consultant_id);

-- Generate service request number function
CREATE OR REPLACE FUNCTION generate_service_request_number()
RETURNS TRIGGER AS $$
DECLARE
  today_str TEXT;
  seq_num INTEGER;
BEGIN
  today_str := TO_CHAR(NOW(), 'YYYYMMDD');
  SELECT COALESCE(MAX(CAST(SPLIT_PART(request_number, '-', 4) AS INTEGER)), 0) + 1
  INTO seq_num
  FROM service_requests
  WHERE request_number LIKE 'SR-' || today_str || '-' || NEW.family_id || '-%';
  NEW.request_number := 'SR-' || today_str || '-' || NEW.family_id || '-' || LPAD(seq_num::TEXT, 3, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_generate_service_request_number ON service_requests;
CREATE TRIGGER trigger_generate_service_request_number
BEFORE INSERT ON service_requests
FOR EACH ROW EXECUTE FUNCTION generate_service_request_number();

-- Enable RLS on service request tables
ALTER TABLE service_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_request_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_deliverables ENABLE ROW LEVEL SECURITY;
ALTER TABLE family_advisor_associations ENABLE ROW LEVEL SECURITY;

-- Service Requests RLS policies
CREATE POLICY "Consultants can view their service requests" ON service_requests 
FOR SELECT USING (auth.uid() = consultant_id);

CREATE POLICY "Consultants can update their service requests" ON service_requests 
FOR UPDATE USING (auth.uid() = consultant_id);

CREATE POLICY "Advisors can view family service requests" ON service_requests 
FOR SELECT USING (
  EXISTS (SELECT 1 FROM families WHERE families.id = service_requests.family_id AND families.advisor_id = auth.uid())
);

CREATE POLICY "Advisors can create service requests" ON service_requests 
FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM families WHERE families.id = service_requests.family_id AND families.advisor_id = auth.uid())
);

-- Service Request Items RLS policies
CREATE POLICY "Users can view service request items" ON service_request_items 
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM service_requests sr 
    WHERE sr.id = service_request_items.service_request_id 
    AND (sr.consultant_id = auth.uid() OR EXISTS (
      SELECT 1 FROM families WHERE families.id = sr.family_id AND families.advisor_id = auth.uid()
    ))
  )
);

CREATE POLICY "Consultants can add items to their requests" ON service_request_items 
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM service_requests sr 
    WHERE sr.id = service_request_items.service_request_id 
    AND sr.consultant_id = auth.uid()
  )
);

-- Service Deliverables RLS policies
CREATE POLICY "Users can view deliverables" ON service_deliverables 
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM service_requests sr 
    WHERE sr.id = service_deliverables.service_request_id 
    AND (sr.consultant_id = auth.uid() OR EXISTS (
      SELECT 1 FROM families WHERE families.id = sr.family_id AND families.advisor_id = auth.uid()
    ))
  )
);

CREATE POLICY "Consultants can manage deliverables" ON service_deliverables 
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM service_requests sr 
    WHERE sr.id = service_deliverables.service_request_id 
    AND sr.consultant_id = auth.uid()
  )
);

-- Family Advisor Associations RLS policies
CREATE POLICY "Consultants can view their associations" ON family_advisor_associations 
FOR SELECT USING (auth.uid() = consultant_id);

CREATE POLICY "Advisors can manage associations for their families" ON family_advisor_associations 
FOR ALL USING (
  EXISTS (SELECT 1 FROM families WHERE families.id = family_advisor_associations.family_id AND families.advisor_id = auth.uid())
);

-- Enable realtime for service_requests
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE service_requests;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

-- Auto-decline/cancel functions for service requests
CREATE OR REPLACE FUNCTION auto_decline_expired_requests()
RETURNS INTEGER AS $$
DECLARE
  affected_count INTEGER;
BEGIN
  UPDATE service_requests
  SET status = 'declined_consultant', decline_reason = 'No response within 48 hours (auto-declined)', updated_at = NOW()
  WHERE status = 'pending_consultant' AND consultant_response_deadline < NOW();
  GET DIAGNOSTICS affected_count = ROW_COUNT;
  RETURN affected_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION auto_cancel_unapproved_requests()
RETURNS INTEGER AS $$
DECLARE
  affected_count INTEGER;
BEGIN
  UPDATE service_requests
  SET status = 'cancelled', decline_reason = 'Family did not approve within 7 days (auto-cancelled)', updated_at = NOW()
  WHERE status = 'awaiting_family_approval' AND family_approval_deadline IS NOT NULL AND family_approval_deadline < NOW();
  GET DIAGNOSTICS affected_count = ROW_COUNT;
  RETURN affected_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION process_expired_service_requests()
RETURNS TABLE(auto_declined INTEGER, auto_cancelled INTEGER) AS $$
DECLARE declined_count INTEGER; cancelled_count INTEGER;
BEGIN
  SELECT auto_decline_expired_requests() INTO declined_count;
  SELECT auto_cancel_unapproved_requests() INTO cancelled_count;
  RETURN QUERY SELECT declined_count, cancelled_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- SEED DATA
-- ============================================

-- Seed service types
INSERT INTO service_types (name, description, icon, category, sort_order) VALUES
('Tax Planning', 'Strategic tax optimization and compliance planning', 'Calculator', 'financial', 1),
('Investment Advisory', 'Portfolio management and investment strategy', 'TrendingUp', 'financial', 2),
('Wealth Management', 'Comprehensive wealth preservation and growth strategies', 'Wallet', 'financial', 3),
('Estate Planning', 'Wills, trusts, and estate transfer planning', 'FileText', 'legal', 10),
('Trust Administration', 'Management and administration of family trusts', 'Building', 'legal', 11),
('Succession Planning', 'Business and leadership succession strategies', 'Users', 'legal', 13),
('Family Governance', 'Family constitution and governance frameworks', 'Home', 'family', 20),
('Next Generation Education', 'Financial literacy and leadership for heirs', 'GraduationCap', 'family', 21),
('Conflict Resolution', 'Mediation and conflict management', 'Scale', 'family', 23),
('Business Advisory', 'Strategic business consulting and planning', 'BarChart', 'business', 30)
ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  category = EXCLUDED.category,
  sort_order = EXCLUDED.sort_order;

-- Update existing families with invite codes
UPDATE families SET invite_code = generate_invite_code() WHERE invite_code IS NULL;

-- ============================================
-- STORAGE (Run separately in Supabase Dashboard)
-- ============================================
-- 
-- 1. Go to Storage in Supabase Dashboard
-- 2. Create bucket "avatars" with:
--    - Public: true
--    - File size limit: 5MB
--    - Allowed MIME types: image/jpeg, image/png, image/gif, image/webp
-- 
-- Policies will be auto-created, or add manually:
-- - INSERT: auth.uid()::text = (storage.foldername(name))[1]
-- - UPDATE: auth.uid()::text = (storage.foldername(name))[1]  
-- - DELETE: auth.uid()::text = (storage.foldername(name))[1]
-- - SELECT: true (public read)
-- ============================================

-- Done!
SELECT 'Database schema created successfully!' as status;
