-- Migration: Add onboarding and stripe fields to profiles
-- Description: Add fields for tracking onboarding progress, profile status, and Stripe integration

-- Add new columns to profiles table
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS is_first_login BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS onboarding_progress INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS profile_status TEXT DEFAULT 'draft', -- 'draft', 'submitted', 'approved', 'rejected', 'revision_required'
ADD COLUMN IF NOT EXISTS stripe_account_id TEXT,
ADD COLUMN IF NOT EXISTS stripe_account_status TEXT DEFAULT 'not_started', -- 'not_started', 'initiated', 'pending', 'active', 'failed'
ADD COLUMN IF NOT EXISTS kyc_status TEXT DEFAULT 'not_started', -- 'not_started', 'pending', 'verified', 'failed'
ADD COLUMN IF NOT EXISTS kyc_submitted_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS kyc_verified_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS subscription_plan TEXT DEFAULT 'free', -- 'free', 'starter', 'professional', 'enterprise'
ADD COLUMN IF NOT EXISTS subscription_status TEXT DEFAULT 'inactive', -- 'inactive', 'active', 'cancelled', 'past_due'
ADD COLUMN IF NOT EXISTS subscription_expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- Create service_types taxonomy table
CREATE TABLE IF NOT EXISTS service_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  icon TEXT, -- Icon name or class
  category TEXT, -- 'financial', 'legal', 'family', 'business', 'personal'
  is_active BOOLEAN DEFAULT TRUE,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add service_type_id to services table
ALTER TABLE services
ADD COLUMN IF NOT EXISTS service_type_id BIGINT REFERENCES service_types(id),
ADD COLUMN IF NOT EXISTS rate DECIMAL(10, 2),
ADD COLUMN IF NOT EXISTS rate_type TEXT DEFAULT 'hourly', -- 'hourly', 'fixed', 'retainer'
ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS max_clients INTEGER,
ADD COLUMN IF NOT EXISTS current_clients INTEGER DEFAULT 0;

-- Create onboarding_steps tracking table
CREATE TABLE IF NOT EXISTS onboarding_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  step_name TEXT NOT NULL, -- 'profile_basics', 'credentials', 'services', 'stripe_setup', 'availability'
  completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMP WITH TIME ZONE,
  data JSONB, -- Store step-specific data
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(advisor_id, step_name)
);

-- Create availability_settings table for consultations
CREATE TABLE IF NOT EXISTS availability_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE UNIQUE,
  timezone TEXT DEFAULT 'America/New_York',
  buffer_before_minutes INTEGER DEFAULT 15,
  buffer_after_minutes INTEGER DEFAULT 15,
  min_notice_hours INTEGER DEFAULT 24,
  max_advance_days INTEGER DEFAULT 60,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create weekly_schedule for recurring availability
CREATE TABLE IF NOT EXISTS weekly_schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  day_of_week INTEGER NOT NULL, -- 0 = Sunday, 6 = Saturday
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  is_available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(advisor_id, day_of_week, start_time)
);

-- Create blocked_dates for vacation/unavailable dates
CREATE TABLE IF NOT EXISTS blocked_dates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(advisor_id, date)
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_profiles_stripe_account_id ON profiles(stripe_account_id);
CREATE INDEX IF NOT EXISTS idx_profiles_profile_status ON profiles(profile_status);
CREATE INDEX IF NOT EXISTS idx_profiles_kyc_status ON profiles(kyc_status);
CREATE INDEX IF NOT EXISTS idx_services_service_type_id ON services(service_type_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_steps_advisor_id ON onboarding_steps(advisor_id);
CREATE INDEX IF NOT EXISTS idx_weekly_schedule_advisor_id ON weekly_schedule(advisor_id);
CREATE INDEX IF NOT EXISTS idx_blocked_dates_advisor_date ON blocked_dates(advisor_id, date);

-- RLS Policies for new tables
ALTER TABLE service_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service types are viewable by everyone" ON service_types FOR SELECT USING (true);

ALTER TABLE onboarding_steps ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Advisors can manage their onboarding steps" ON onboarding_steps FOR ALL USING (auth.uid() = advisor_id);

ALTER TABLE availability_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Advisors can manage their availability settings" ON availability_settings FOR ALL USING (auth.uid() = advisor_id);

ALTER TABLE weekly_schedule ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Advisors can manage their weekly schedule" ON weekly_schedule FOR ALL USING (auth.uid() = advisor_id);

ALTER TABLE blocked_dates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Advisors can manage their blocked dates" ON blocked_dates FOR ALL USING (auth.uid() = advisor_id);
