-- Migration: Add availability settings tables for calendar scheduling
-- Description: Tables for managing advisor availability, weekly schedule, and blocked dates

-- Availability Settings - per-advisor configuration
CREATE TABLE IF NOT EXISTS availability_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE UNIQUE,
  timezone TEXT DEFAULT 'America/New_York',
  buffer_before_minutes INTEGER DEFAULT 15,
  buffer_after_minutes INTEGER DEFAULT 15,
  min_notice_hours INTEGER DEFAULT 24,
  max_advance_days INTEGER DEFAULT 60,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Weekly Schedule - recurring availability slots
CREATE TABLE IF NOT EXISTS weekly_schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  day_of_week INTEGER NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6), -- 0 = Sunday, 6 = Saturday
  start_time TEXT NOT NULL, -- Format: "HH:MM" e.g. "09:00"
  end_time TEXT NOT NULL,   -- Format: "HH:MM" e.g. "17:00"
  is_available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Blocked Dates - specific dates that are unavailable
CREATE TABLE IF NOT EXISTS blocked_dates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_availability_settings_advisor_id ON availability_settings(advisor_id);
CREATE INDEX IF NOT EXISTS idx_weekly_schedule_advisor_id ON weekly_schedule(advisor_id);
CREATE INDEX IF NOT EXISTS idx_weekly_schedule_day ON weekly_schedule(day_of_week);
CREATE INDEX IF NOT EXISTS idx_blocked_dates_advisor_id ON blocked_dates(advisor_id);
CREATE INDEX IF NOT EXISTS idx_blocked_dates_date ON blocked_dates(date);

-- RLS Policies

-- Availability Settings
ALTER TABLE availability_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Advisors can view their availability settings" ON availability_settings 
  FOR SELECT USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can insert their availability settings" ON availability_settings 
  FOR INSERT WITH CHECK (auth.uid() = advisor_id);

CREATE POLICY "Advisors can update their availability settings" ON availability_settings 
  FOR UPDATE USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can delete their availability settings" ON availability_settings 
  FOR DELETE USING (auth.uid() = advisor_id);

-- Weekly Schedule
ALTER TABLE weekly_schedule ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Advisors can view their weekly schedule" ON weekly_schedule 
  FOR SELECT USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can insert their weekly schedule" ON weekly_schedule 
  FOR INSERT WITH CHECK (auth.uid() = advisor_id);

CREATE POLICY "Advisors can update their weekly schedule" ON weekly_schedule 
  FOR UPDATE USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can delete their weekly schedule" ON weekly_schedule 
  FOR DELETE USING (auth.uid() = advisor_id);

-- Blocked Dates
ALTER TABLE blocked_dates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Advisors can view their blocked dates" ON blocked_dates 
  FOR SELECT USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can insert their blocked dates" ON blocked_dates 
  FOR INSERT WITH CHECK (auth.uid() = advisor_id);

CREATE POLICY "Advisors can update their blocked dates" ON blocked_dates 
  FOR UPDATE USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can delete their blocked dates" ON blocked_dates 
  FOR DELETE USING (auth.uid() = advisor_id);

-- Update trigger for availability_settings
CREATE OR REPLACE FUNCTION update_availability_settings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_availability_settings_updated_at
BEFORE UPDATE ON availability_settings
FOR EACH ROW EXECUTE FUNCTION update_availability_settings_updated_at();
