-- Migration: Add knowledge resources tables
-- Description: Tables for managing educational resources, articles, and learning paths

-- Knowledge Resources (articles, guides, documents, etc.)
CREATE TABLE IF NOT EXISTS knowledge_resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  type TEXT NOT NULL DEFAULT 'document', -- 'document', 'article', 'video', 'podcast', 'template', 'guide', 'link', 'checklist', 'learning-path'
  category TEXT DEFAULT 'General',
  content TEXT, -- For articles, the HTML/markdown content
  file_url TEXT, -- For uploaded files
  external_url TEXT, -- For external links/videos
  thumbnail_url TEXT,
  is_featured BOOLEAN DEFAULT FALSE,
  is_published BOOLEAN DEFAULT TRUE,
  view_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Resource Shares (tracking which families have access to which resources)
CREATE TABLE IF NOT EXISTS resource_shares (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT REFERENCES knowledge_resources(id) ON DELETE CASCADE,
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE,
  shared_by UUID REFERENCES profiles(id),
  shared_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(resource_id, family_id)
);

-- Learning Paths (structured courses)
CREATE TABLE IF NOT EXISTS learning_paths (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  difficulty TEXT DEFAULT 'beginner', -- 'beginner', 'intermediate', 'advanced'
  estimated_duration_minutes INTEGER,
  is_published BOOLEAN DEFAULT TRUE,
  thumbnail_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Learning Path Steps (lessons within a learning path)
CREATE TABLE IF NOT EXISTS learning_path_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  learning_path_id BIGINT REFERENCES learning_paths(id) ON DELETE CASCADE,
  resource_id BIGINT REFERENCES knowledge_resources(id) ON DELETE SET NULL, -- Optional link to a resource
  title TEXT NOT NULL,
  description TEXT,
  content TEXT,
  step_order INTEGER NOT NULL,
  estimated_duration_minutes INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Constitution Templates (special type of resource)
CREATE TABLE IF NOT EXISTS constitution_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  is_default BOOLEAN DEFAULT FALSE, -- Mark as default template
  is_published BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Constitution Sections (12 standard sections)
CREATE TABLE IF NOT EXISTS constitution_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT REFERENCES constitution_templates(id) ON DELETE CASCADE,
  section_number INTEGER NOT NULL,
  title TEXT NOT NULL,
  content TEXT,
  is_required BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_knowledge_resources_advisor_id ON knowledge_resources(advisor_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_resources_type ON knowledge_resources(type);
CREATE INDEX IF NOT EXISTS idx_knowledge_resources_category ON knowledge_resources(category);
CREATE INDEX IF NOT EXISTS idx_resource_shares_resource_id ON resource_shares(resource_id);
CREATE INDEX IF NOT EXISTS idx_resource_shares_family_id ON resource_shares(family_id);
CREATE INDEX IF NOT EXISTS idx_learning_paths_advisor_id ON learning_paths(advisor_id);
CREATE INDEX IF NOT EXISTS idx_learning_path_steps_path_id ON learning_path_steps(learning_path_id);
CREATE INDEX IF NOT EXISTS idx_constitution_templates_advisor_id ON constitution_templates(advisor_id);
CREATE INDEX IF NOT EXISTS idx_constitution_sections_template_id ON constitution_sections(template_id);

-- RLS Policies

-- Knowledge Resources
ALTER TABLE knowledge_resources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Advisors can view their resources" ON knowledge_resources 
  FOR SELECT USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can insert their resources" ON knowledge_resources 
  FOR INSERT WITH CHECK (auth.uid() = advisor_id);

CREATE POLICY "Advisors can update their resources" ON knowledge_resources 
  FOR UPDATE USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can delete their resources" ON knowledge_resources 
  FOR DELETE USING (auth.uid() = advisor_id);

-- Resource Shares
ALTER TABLE resource_shares ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Advisors can view their shared resources" ON resource_shares 
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM knowledge_resources WHERE id = resource_shares.resource_id AND advisor_id = auth.uid())
  );

CREATE POLICY "Advisors can share their resources" ON resource_shares 
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM knowledge_resources WHERE id = resource_shares.resource_id AND advisor_id = auth.uid())
  );

CREATE POLICY "Advisors can unshare their resources" ON resource_shares 
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM knowledge_resources WHERE id = resource_shares.resource_id AND advisor_id = auth.uid())
  );

-- Learning Paths
ALTER TABLE learning_paths ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Advisors can manage their learning paths" ON learning_paths FOR ALL USING (auth.uid() = advisor_id);

-- Learning Path Steps
ALTER TABLE learning_path_steps ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Advisors can manage their learning path steps" ON learning_path_steps FOR ALL USING (
  EXISTS (SELECT 1 FROM learning_paths WHERE id = learning_path_steps.learning_path_id AND advisor_id = auth.uid())
);

-- Constitution Templates
ALTER TABLE constitution_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Advisors can manage their constitution templates" ON constitution_templates FOR ALL USING (auth.uid() = advisor_id);

-- Constitution Sections
ALTER TABLE constitution_sections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Advisors can manage their constitution sections" ON constitution_sections FOR ALL USING (
  EXISTS (SELECT 1 FROM constitution_templates WHERE id = constitution_sections.template_id AND advisor_id = auth.uid())
);

-- Update triggers
CREATE OR REPLACE FUNCTION update_knowledge_resource_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_knowledge_resource_updated_at
BEFORE UPDATE ON knowledge_resources
FOR EACH ROW EXECUTE FUNCTION update_knowledge_resource_updated_at();

CREATE TRIGGER trigger_update_learning_path_updated_at
BEFORE UPDATE ON learning_paths
FOR EACH ROW EXECUTE FUNCTION update_knowledge_resource_updated_at();

CREATE TRIGGER trigger_update_constitution_template_updated_at
BEFORE UPDATE ON constitution_templates
FOR EACH ROW EXECUTE FUNCTION update_knowledge_resource_updated_at();
