-- Migration: Add push notifications support
-- Description: Tables for storing push notification subscriptions

-- Push Subscriptions (Web Push API subscriptions)
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh_key TEXT NOT NULL,
  auth_key TEXT NOT NULL,
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Notification Preferences (per-user settings)
CREATE TABLE IF NOT EXISTS notification_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  -- Push notification toggles
  push_enabled BOOLEAN DEFAULT TRUE,
  push_messages BOOLEAN DEFAULT TRUE,
  push_consultations BOOLEAN DEFAULT TRUE,
  push_payments BOOLEAN DEFAULT TRUE,
  push_updates BOOLEAN DEFAULT TRUE,
  push_alerts BOOLEAN DEFAULT TRUE,
  -- Email notification toggles
  email_enabled BOOLEAN DEFAULT TRUE,
  email_messages BOOLEAN DEFAULT TRUE,
  email_consultations BOOLEAN DEFAULT TRUE,
  email_payments BOOLEAN DEFAULT TRUE,
  email_weekly_digest BOOLEAN DEFAULT TRUE,
  -- Quiet hours
  quiet_hours_enabled BOOLEAN DEFAULT FALSE,
  quiet_hours_start TIME DEFAULT '22:00',
  quiet_hours_end TIME DEFAULT '08:00',
  -- Timezone for quiet hours
  timezone TEXT DEFAULT 'UTC',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_id ON push_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_notification_preferences_user_id ON notification_preferences(user_id);

-- RLS Policies
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;

-- Users can manage their own subscriptions
CREATE POLICY "Users can view their push subscriptions" ON push_subscriptions 
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their push subscriptions" ON push_subscriptions 
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their push subscriptions" ON push_subscriptions 
  FOR DELETE USING (auth.uid() = user_id);

-- Users can manage their own preferences
CREATE POLICY "Users can view their notification preferences" ON notification_preferences 
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their notification preferences" ON notification_preferences 
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their notification preferences" ON notification_preferences 
  FOR UPDATE USING (auth.uid() = user_id);

-- Update trigger
CREATE TRIGGER trigger_update_push_subscription_updated_at
BEFORE UPDATE ON push_subscriptions
FOR EACH ROW EXECUTE FUNCTION update_knowledge_resource_updated_at();

CREATE TRIGGER trigger_update_notification_preferences_updated_at
BEFORE UPDATE ON notification_preferences
FOR EACH ROW EXECUTE FUNCTION update_knowledge_resource_updated_at();

-- Create default preferences when user signs up
CREATE OR REPLACE FUNCTION create_default_notification_preferences()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO notification_preferences (user_id)
  VALUES (NEW.id)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to create default preferences
CREATE TRIGGER trigger_create_notification_preferences
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION create_default_notification_preferences();
