-- Migration: Add profile experience, education, skills, and recommendations tables
-- Description: Tables for managing advisor profile sections

-- EXPERIENCE (Work history)
CREATE TABLE IF NOT EXISTS experience (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  company TEXT NOT NULL,
  start_date DATE,
  end_date DATE, -- NULL means current position
  is_current BOOLEAN DEFAULT FALSE,
  description TEXT,
  location TEXT,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- EDUCATION (Academic qualifications)
CREATE TABLE IF NOT EXISTS education (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  degree TEXT NOT NULL,
  institution TEXT NOT NULL,
  field_of_study TEXT,
  start_year TEXT,
  end_year TEXT,
  grade TEXT,
  description TEXT,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- SKILLS (Professional skills and competencies)
CREATE TABLE IF NOT EXISTS skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  proficiency TEXT DEFAULT 'intermediate', -- 'beginner', 'intermediate', 'expert'
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(advisor_id, name)
);

-- RECOMMENDATIONS (Client testimonials and reviews)
CREATE TABLE IF NOT EXISTS recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  author_title TEXT,
  author_company TEXT,
  author_avatar_url TEXT,
  relationship TEXT, -- 'client', 'colleague', 'supervisor', etc.
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  text TEXT NOT NULL,
  is_featured BOOLEAN DEFAULT FALSE,
  is_visible BOOLEAN DEFAULT TRUE,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_experience_advisor_id ON experience(advisor_id);
CREATE INDEX IF NOT EXISTS idx_education_advisor_id ON education(advisor_id);
CREATE INDEX IF NOT EXISTS idx_skills_advisor_id ON skills(advisor_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_advisor_id ON recommendations(advisor_id);

-- Enable RLS
ALTER TABLE experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE education ENABLE ROW LEVEL SECURITY;
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE recommendations ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Experience
CREATE POLICY "Advisors can view their own experience"
  ON experience FOR SELECT
  USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can insert their own experience"
  ON experience FOR INSERT
  WITH CHECK (auth.uid() = advisor_id);

CREATE POLICY "Advisors can update their own experience"
  ON experience FOR UPDATE
  USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can delete their own experience"
  ON experience FOR DELETE
  USING (auth.uid() = advisor_id);

-- RLS Policies for Education
CREATE POLICY "Advisors can view their own education"
  ON education FOR SELECT
  USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can insert their own education"
  ON education FOR INSERT
  WITH CHECK (auth.uid() = advisor_id);

CREATE POLICY "Advisors can update their own education"
  ON education FOR UPDATE
  USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can delete their own education"
  ON education FOR DELETE
  USING (auth.uid() = advisor_id);

-- RLS Policies for Skills
CREATE POLICY "Advisors can view their own skills"
  ON skills FOR SELECT
  USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can insert their own skills"
  ON skills FOR INSERT
  WITH CHECK (auth.uid() = advisor_id);

CREATE POLICY "Advisors can update their own skills"
  ON skills FOR UPDATE
  USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can delete their own skills"
  ON skills FOR DELETE
  USING (auth.uid() = advisor_id);

-- RLS Policies for Recommendations
CREATE POLICY "Advisors can view their own recommendations"
  ON recommendations FOR SELECT
  USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can insert their own recommendations"
  ON recommendations FOR INSERT
  WITH CHECK (auth.uid() = advisor_id);

CREATE POLICY "Advisors can update their own recommendations"
  ON recommendations FOR UPDATE
  USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can delete their own recommendations"
  ON recommendations FOR DELETE
  USING (auth.uid() = advisor_id);

-- Public read policies (optional - for public profiles)
-- Uncomment if you want these sections to be publicly viewable
-- CREATE POLICY "Public can view advisor experience"
--   ON experience FOR SELECT
--   TO anon
--   USING (true);

-- CREATE POLICY "Public can view advisor education"
--   ON education FOR SELECT
--   TO anon
--   USING (true);

-- CREATE POLICY "Public can view advisor skills"
--   ON skills FOR SELECT
--   TO anon
--   USING (true);

-- CREATE POLICY "Public can view visible recommendations"
--   ON recommendations FOR SELECT
--   TO anon
--   USING (is_visible = true);
