-- Add conversation_participants table for managing participants in conversations
-- This allows adding/removing specific participants to conversations beyond the family members

CREATE TABLE IF NOT EXISTS conversation_participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT REFERENCES conversations(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  family_member_id BIGINT REFERENCES family_members(id) ON DELETE CASCADE,
  participant_name TEXT NOT NULL,
  role TEXT DEFAULT 'member', -- 'owner', 'member'
  added_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  added_by UUID REFERENCES auth.users(id),
  UNIQUE(conversation_id, user_id),
  UNIQUE(conversation_id, family_member_id)
);

-- Enable RLS
ALTER TABLE conversation_participants ENABLE ROW LEVEL SECURITY;

-- Advisors can view participants in their conversations
CREATE POLICY "Advisors can view conversation participants" ON conversation_participants FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM conversations 
    JOIN families ON families.id = conversations.family_id 
    WHERE conversations.id = conversation_participants.conversation_id 
    AND families.advisor_id = auth.uid()
  )
);

-- Advisors can manage participants in their conversations
CREATE POLICY "Advisors can manage conversation participants" ON conversation_participants FOR ALL USING (
  EXISTS (
    SELECT 1 FROM conversations 
    JOIN families ON families.id = conversations.family_id 
    WHERE conversations.id = conversation_participants.conversation_id 
    AND families.advisor_id = auth.uid()
  )
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_conversation_participants_conversation_id 
  ON conversation_participants(conversation_id);
CREATE INDEX IF NOT EXISTS idx_conversation_participants_user_id 
  ON conversation_participants(user_id);
