-- ============================================
-- Migration: Knowledge Center Epic Update
-- ============================================
-- Adds:
-- 1. resource_folders table for folder organization
-- 2. deleted_at column for soft delete
-- 3. folder_id reference in knowledge_resources
-- 4. Version support in resource_shares with snapshots
-- 5. Updated RLS policies
-- ============================================

-- ============================================
-- 1. RESOURCE FOLDERS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS resource_folders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advisor_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT unique_folder_name_per_advisor UNIQUE (advisor_id, name)
);

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_resource_folders_advisor_id ON resource_folders(advisor_id);

-- Enable RLS
ALTER TABLE resource_folders ENABLE ROW LEVEL SECURITY;

-- RLS Policies for resource_folders
DROP POLICY IF EXISTS "Advisors can manage their folders" ON resource_folders;
CREATE POLICY "Advisors can manage their folders" ON resource_folders 
  FOR ALL USING (auth.uid() = advisor_id);

-- ============================================
-- 2. UPDATE KNOWLEDGE_RESOURCES TABLE
-- ============================================

-- Add deleted_at for soft delete
ALTER TABLE knowledge_resources 
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;

-- Add folder_id reference
ALTER TABLE knowledge_resources 
  ADD COLUMN IF NOT EXISTS folder_id BIGINT REFERENCES resource_folders(id) ON DELETE SET NULL;

-- Index for soft delete queries (exclude deleted)
CREATE INDEX IF NOT EXISTS idx_knowledge_resources_deleted_at ON knowledge_resources(deleted_at);
CREATE INDEX IF NOT EXISTS idx_knowledge_resources_folder_id ON knowledge_resources(folder_id);

-- ============================================
-- 3. UPDATE RESOURCE_SHARES TABLE FOR VERSIONING
-- ============================================

-- Add version tracking
ALTER TABLE resource_shares 
  ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1;

-- Add resource snapshot (immutable copy at time of sharing)
ALTER TABLE resource_shares 
  ADD COLUMN IF NOT EXISTS resource_snapshot JSONB;

-- Add advisor_id for easier queries from family side
ALTER TABLE resource_shares 
  ADD COLUMN IF NOT EXISTS advisor_id UUID REFERENCES profiles(id);

-- Remove unique constraint to allow multiple versions of same resource for same family
ALTER TABLE resource_shares 
  DROP CONSTRAINT IF EXISTS resource_shares_resource_id_family_id_key;

-- Create new index for queries
CREATE INDEX IF NOT EXISTS idx_resource_shares_family_id ON resource_shares(family_id);
CREATE INDEX IF NOT EXISTS idx_resource_shares_advisor_id ON resource_shares(advisor_id);

-- Rename shared_at to created_at for consistency (if exists)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns 
             WHERE table_name = 'resource_shares' AND column_name = 'shared_at') THEN
    ALTER TABLE resource_shares RENAME COLUMN shared_at TO created_at;
  END IF;
END $$;

-- Add created_at if it doesn't exist
ALTER TABLE resource_shares 
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- ============================================
-- 4. UPDATE CONSTITUTION TEMPLATES
-- ============================================

-- Add content field for storing all sections as JSON
ALTER TABLE constitution_templates 
  ADD COLUMN IF NOT EXISTS sections_content JSONB DEFAULT '{}';

-- ============================================
-- 5. UPDATE RLS POLICIES
-- ============================================

-- Update knowledge_resources policy to exclude soft-deleted
DROP POLICY IF EXISTS "Advisors can manage resources" ON knowledge_resources;
CREATE POLICY "Advisors can view their resources" ON knowledge_resources 
  FOR SELECT USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can insert resources" ON knowledge_resources 
  FOR INSERT WITH CHECK (auth.uid() = advisor_id);

CREATE POLICY "Advisors can update their resources" ON knowledge_resources 
  FOR UPDATE USING (auth.uid() = advisor_id);

CREATE POLICY "Advisors can delete their resources" ON knowledge_resources 
  FOR DELETE USING (auth.uid() = advisor_id);

-- Update resource_shares policy
DROP POLICY IF EXISTS "Advisors can manage shares" ON resource_shares;
CREATE POLICY "Advisors can manage their shares" ON resource_shares 
  FOR ALL USING (
    EXISTS (SELECT 1 FROM knowledge_resources WHERE id = resource_shares.resource_id AND advisor_id = auth.uid())
    OR advisor_id = auth.uid()
  );

-- Family members can view shared resources
DROP POLICY IF EXISTS "Families can view shared resources" ON resource_shares;
CREATE POLICY "Families can view shared resources" ON resource_shares 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM families f
      JOIN family_members fm ON fm.family_id = f.id
      WHERE f.id = resource_shares.family_id
      -- Note: This needs proper family member auth check when family portal auth is implemented
    )
  );

-- ============================================
-- 6. HELPER FUNCTION FOR CREATING RESOURCE SNAPSHOTS
-- ============================================

CREATE OR REPLACE FUNCTION create_resource_snapshot(p_resource_id BIGINT)
RETURNS JSONB AS $$
DECLARE
  v_snapshot JSONB;
BEGIN
  SELECT jsonb_build_object(
    'id', id,
    'title', title,
    'description', description,
    'type', type,
    'category', category,
    'content', content,
    'external_url', external_url,
    'is_featured', is_featured,
    'created_at', created_at,
    'snapshot_created_at', NOW()
  ) INTO v_snapshot
  FROM knowledge_resources
  WHERE id = p_resource_id AND deleted_at IS NULL;
  
  RETURN v_snapshot;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 7. TRIGGER FOR UPDATED_AT ON FOLDERS
-- ============================================

CREATE OR REPLACE FUNCTION update_folder_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_folder_updated_at ON resource_folders;
CREATE TRIGGER trigger_update_folder_updated_at
  BEFORE UPDATE ON resource_folders
  FOR EACH ROW EXECUTE FUNCTION update_folder_updated_at();

-- ============================================
-- 8. BACKFILL ADVISOR_ID IN RESOURCE_SHARES
-- ============================================

UPDATE resource_shares rs
SET advisor_id = kr.advisor_id
FROM knowledge_resources kr
WHERE rs.resource_id = kr.id AND rs.advisor_id IS NULL;

-- ============================================
-- Done!
-- ============================================
SELECT 'Knowledge Center Epic migration completed successfully!' as status;
