-- Migration: Add learning paths tables with modules and resources
-- Description: Tables for structured learning paths with modules and resources

-- Add category column to learning_paths table if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'learning_paths' AND column_name = 'category'
  ) THEN
    ALTER TABLE learning_paths ADD COLUMN category TEXT DEFAULT 'general';
  END IF;
END $$;

-- Learning Modules (groups of resources within a learning path)
CREATE TABLE IF NOT EXISTS learning_modules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  learning_path_id BIGINT REFERENCES learning_paths(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  order_index INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Learning Resources (individual content items within a module)
CREATE TABLE IF NOT EXISTS learning_resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id BIGINT REFERENCES learning_modules(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'article' CHECK (type IN ('video', 'article', 'guide', 'document', 'link')),
  duration TEXT, -- e.g., '15 min', '1h 30m'
  content_url TEXT,
  order_index INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_learning_modules_path_id ON learning_modules(learning_path_id);
CREATE INDEX IF NOT EXISTS idx_learning_modules_order ON learning_modules(learning_path_id, order_index);
CREATE INDEX IF NOT EXISTS idx_learning_resources_module_id ON learning_resources(module_id);
CREATE INDEX IF NOT EXISTS idx_learning_resources_order ON learning_resources(module_id, order_index);

-- RLS Policies for Learning Modules
ALTER TABLE learning_modules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Advisors can view their learning modules" ON learning_modules 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM learning_paths 
      WHERE learning_paths.id = learning_modules.learning_path_id 
      AND learning_paths.advisor_id = auth.uid()
    )
  );

CREATE POLICY "Advisors can insert their learning modules" ON learning_modules 
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM learning_paths 
      WHERE learning_paths.id = learning_modules.learning_path_id 
      AND learning_paths.advisor_id = auth.uid()
    )
  );

CREATE POLICY "Advisors can update their learning modules" ON learning_modules 
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM learning_paths 
      WHERE learning_paths.id = learning_modules.learning_path_id 
      AND learning_paths.advisor_id = auth.uid()
    )
  );

CREATE POLICY "Advisors can delete their learning modules" ON learning_modules 
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM learning_paths 
      WHERE learning_paths.id = learning_modules.learning_path_id 
      AND learning_paths.advisor_id = auth.uid()
    )
  );

-- RLS Policies for Learning Resources
ALTER TABLE learning_resources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Advisors can view their learning resources" ON learning_resources 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM learning_modules 
      JOIN learning_paths ON learning_paths.id = learning_modules.learning_path_id
      WHERE learning_modules.id = learning_resources.module_id 
      AND learning_paths.advisor_id = auth.uid()
    )
  );

CREATE POLICY "Advisors can insert their learning resources" ON learning_resources 
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM learning_modules 
      JOIN learning_paths ON learning_paths.id = learning_modules.learning_path_id
      WHERE learning_modules.id = learning_resources.module_id 
      AND learning_paths.advisor_id = auth.uid()
    )
  );

CREATE POLICY "Advisors can update their learning resources" ON learning_resources 
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM learning_modules 
      JOIN learning_paths ON learning_paths.id = learning_modules.learning_path_id
      WHERE learning_modules.id = learning_resources.module_id 
      AND learning_paths.advisor_id = auth.uid()
    )
  );

CREATE POLICY "Advisors can delete their learning resources" ON learning_resources 
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM learning_modules 
      JOIN learning_paths ON learning_paths.id = learning_modules.learning_path_id
      WHERE learning_modules.id = learning_resources.module_id 
      AND learning_paths.advisor_id = auth.uid()
    )
  );

-- Update trigger for learning_modules
CREATE OR REPLACE FUNCTION update_learning_module_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_learning_module_updated_at
BEFORE UPDATE ON learning_modules
FOR EACH ROW EXECUTE FUNCTION update_learning_module_updated_at();

-- Update trigger for learning_resources
CREATE OR REPLACE FUNCTION update_learning_resource_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_learning_resource_updated_at
BEFORE UPDATE ON learning_resources
FOR EACH ROW EXECUTE FUNCTION update_learning_resource_updated_at();
