-- ============================================
-- Service Requests Migration
-- MVP1: Service Request Journey
-- EPIC-014 to EPIC-021
-- ============================================

-- SERVICE REQUESTS - Main engagement record
-- Tracks the lifecycle of service booking from family to consultant
CREATE TABLE IF NOT EXISTS service_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Request ID format: SR-[YYYYMMDD]-[FAMILY_ID]-[SEQUENCE]
  request_number TEXT UNIQUE,
  
  -- Relationships
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE NOT NULL,
  consultant_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  original_service_id BIGINT REFERENCES services(id) ON DELETE SET NULL,
  
  -- Status tracking
  status TEXT DEFAULT 'pending_consultant' NOT NULL,
  -- Status values:
  -- 'pending_consultant' - Waiting for consultant to review (48h deadline)
  -- 'awaiting_family_approval' - Consultant accepted, waiting for family
  -- 'in_progress' - Family approved, consultant has access
  -- 'delivered' - Consultant marked complete
  -- 'completed_paid' - Family confirmed & paid
  -- 'declined_consultant' - Consultant declined
  -- 'declined_family' - Family declined after consultant proposal
  -- 'cancelled' - Auto-cancelled (timeout)
  
  -- Notes and comments
  family_notes TEXT, -- Optional notes from family at booking
  consultant_comment TEXT, -- Explanation for additional services
  decline_reason TEXT, -- Reason if declined
  
  -- Pricing
  original_amount DECIMAL(10, 2), -- Original service price
  additional_amount DECIMAL(10, 2) DEFAULT 0, -- Sum of additional services
  total_amount DECIMAL(10, 2), -- Final total
  
  -- Timeline
  estimated_timeline TEXT, -- e.g., "2 weeks"
  
  -- Payment
  stripe_payment_intent_id TEXT,
  stripe_invoice_id TEXT,
  
  -- Timestamps
  booked_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  consultant_response_deadline TIMESTAMP WITH TIME ZONE DEFAULT (NOW() + INTERVAL '48 hours'),
  consultant_confirmed_at TIMESTAMP WITH TIME ZONE,
  family_approval_deadline TIMESTAMP WITH TIME ZONE, -- Set when consultant confirms (7 days)
  family_approved_at TIMESTAMP WITH TIME ZONE,
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  paid_at TIMESTAMP WITH TIME ZONE,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- SERVICE REQUEST ITEMS - Individual services within a request
-- Supports both original service and consultant-added services
CREATE TABLE IF NOT EXISTS service_request_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT REFERENCES service_requests(id) ON DELETE CASCADE NOT NULL,
  service_id BIGINT REFERENCES services(id) ON DELETE SET NULL,
  
  -- Item details (snapshot at booking time)
  service_name TEXT NOT NULL,
  service_description TEXT,
  price_at_booking DECIMAL(10, 2) NOT NULL,
  
  -- Who added this
  is_original BOOLEAN DEFAULT FALSE, -- True for the initially booked service
  added_by TEXT DEFAULT 'family', -- 'family' or 'consultant'
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- SERVICE DELIVERABLES - Links to completed work
CREATE TABLE IF NOT EXISTS service_deliverables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT REFERENCES service_requests(id) ON DELETE CASCADE NOT NULL,
  
  title TEXT NOT NULL,
  description TEXT,
  external_link TEXT NOT NULL, -- URL to external resource (Google Docs, etc.)
  
  uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- FAMILY ADVISOR ASSOCIATIONS - Access control for consultants
-- Tracks what modules a consultant can access for a family
CREATE TABLE IF NOT EXISTS family_advisor_associations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id BIGINT REFERENCES families(id) ON DELETE CASCADE NOT NULL,
  consultant_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  service_request_id BIGINT REFERENCES service_requests(id) ON DELETE SET NULL,
  
  -- Access level (MVP1: always 'view')
  permission_level TEXT DEFAULT 'view' NOT NULL, -- 'view', 'edit' (future)
  
  -- Modules consultant can access (JSON array)
  modules JSONB DEFAULT '[]'::jsonb, -- e.g., ["constitution", "meetings", "succession"]
  
  -- Status
  status TEXT DEFAULT 'active' NOT NULL, -- 'active', 'revoked', 'expired'
  
  -- Timestamps
  granted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  revoked_at TIMESTAMP WITH TIME ZONE,
  expires_at TIMESTAMP WITH TIME ZONE, -- Optional expiration
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  UNIQUE(family_id, consultant_id, service_request_id)
);

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS idx_service_requests_family_id ON service_requests(family_id);
CREATE INDEX IF NOT EXISTS idx_service_requests_consultant_id ON service_requests(consultant_id);
CREATE INDEX IF NOT EXISTS idx_service_requests_status ON service_requests(status);
CREATE INDEX IF NOT EXISTS idx_service_requests_request_number ON service_requests(request_number);
CREATE INDEX IF NOT EXISTS idx_service_request_items_request_id ON service_request_items(service_request_id);
CREATE INDEX IF NOT EXISTS idx_service_deliverables_request_id ON service_deliverables(service_request_id);
CREATE INDEX IF NOT EXISTS idx_family_advisor_associations_family ON family_advisor_associations(family_id);
CREATE INDEX IF NOT EXISTS idx_family_advisor_associations_consultant ON family_advisor_associations(consultant_id);
CREATE INDEX IF NOT EXISTS idx_family_advisor_associations_status ON family_advisor_associations(status);

-- ============================================
-- FUNCTIONS
-- ============================================

-- Generate service request number
CREATE OR REPLACE FUNCTION generate_service_request_number()
RETURNS TRIGGER AS $$
DECLARE
  today_str TEXT;
  seq_num INTEGER;
BEGIN
  today_str := TO_CHAR(NOW(), 'YYYYMMDD');
  
  -- Get the sequence number for today for this family
  SELECT COALESCE(MAX(
    CAST(SPLIT_PART(request_number, '-', 4) AS INTEGER)
  ), 0) + 1
  INTO seq_num
  FROM service_requests
  WHERE request_number LIKE 'SR-' || today_str || '-' || NEW.family_id || '-%';
  
  NEW.request_number := 'SR-' || today_str || '-' || NEW.family_id || '-' || LPAD(seq_num::TEXT, 3, '0');
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Auto-set consultant response deadline
CREATE OR REPLACE FUNCTION set_consultant_response_deadline()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.consultant_response_deadline IS NULL THEN
    NEW.consultant_response_deadline := NOW() + INTERVAL '48 hours';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Update total_amount when items change
CREATE OR REPLACE FUNCTION update_service_request_total()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE service_requests
  SET 
    original_amount = (
      SELECT COALESCE(SUM(price_at_booking), 0)
      FROM service_request_items
      WHERE service_request_id = COALESCE(NEW.service_request_id, OLD.service_request_id)
        AND is_original = TRUE
    ),
    additional_amount = (
      SELECT COALESCE(SUM(price_at_booking), 0)
      FROM service_request_items
      WHERE service_request_id = COALESCE(NEW.service_request_id, OLD.service_request_id)
        AND is_original = FALSE
    ),
    total_amount = (
      SELECT COALESCE(SUM(price_at_booking), 0)
      FROM service_request_items
      WHERE service_request_id = COALESCE(NEW.service_request_id, OLD.service_request_id)
    ),
    updated_at = NOW()
  WHERE id = COALESCE(NEW.service_request_id, OLD.service_request_id);
  
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- TRIGGERS
-- ============================================

DROP TRIGGER IF EXISTS trigger_generate_service_request_number ON service_requests;
CREATE TRIGGER trigger_generate_service_request_number
BEFORE INSERT ON service_requests
FOR EACH ROW EXECUTE FUNCTION generate_service_request_number();

DROP TRIGGER IF EXISTS trigger_set_consultant_deadline ON service_requests;
CREATE TRIGGER trigger_set_consultant_deadline
BEFORE INSERT ON service_requests
FOR EACH ROW EXECUTE FUNCTION set_consultant_response_deadline();

DROP TRIGGER IF EXISTS trigger_update_request_total_insert ON service_request_items;
CREATE TRIGGER trigger_update_request_total_insert
AFTER INSERT ON service_request_items
FOR EACH ROW EXECUTE FUNCTION update_service_request_total();

DROP TRIGGER IF EXISTS trigger_update_request_total_update ON service_request_items;
CREATE TRIGGER trigger_update_request_total_update
AFTER UPDATE ON service_request_items
FOR EACH ROW EXECUTE FUNCTION update_service_request_total();

DROP TRIGGER IF EXISTS trigger_update_request_total_delete ON service_request_items;
CREATE TRIGGER trigger_update_request_total_delete
AFTER DELETE ON service_request_items
FOR EACH ROW EXECUTE FUNCTION update_service_request_total();

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE service_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_request_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_deliverables ENABLE ROW LEVEL SECURITY;
ALTER TABLE family_advisor_associations ENABLE ROW LEVEL SECURITY;

-- Service Requests policies
-- Drop existing policies first (idempotent)
DROP POLICY IF EXISTS "Consultants can view their service requests" ON service_requests;
DROP POLICY IF EXISTS "Consultants can update their service requests" ON service_requests;
DROP POLICY IF EXISTS "Advisors can view family service requests" ON service_requests;
DROP POLICY IF EXISTS "Advisors can create service requests" ON service_requests;

-- Consultants can view requests assigned to them
CREATE POLICY "Consultants can view their service requests" ON service_requests 
FOR SELECT USING (auth.uid() = consultant_id);

-- Consultants can update their service requests
CREATE POLICY "Consultants can update their service requests" ON service_requests 
FOR UPDATE USING (auth.uid() = consultant_id);

-- Family advisors can view requests for their families
CREATE POLICY "Advisors can view family service requests" ON service_requests 
FOR SELECT USING (
  EXISTS (SELECT 1 FROM families WHERE families.id = service_requests.family_id AND families.advisor_id = auth.uid())
);

-- Family advisors can create requests for their families
CREATE POLICY "Advisors can create service requests" ON service_requests 
FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM families WHERE families.id = service_requests.family_id AND families.advisor_id = auth.uid())
);

-- Service Request Items policies
DROP POLICY IF EXISTS "Users can view service request items" ON service_request_items;
DROP POLICY IF EXISTS "Consultants can add items to their requests" ON service_request_items;

CREATE POLICY "Users can view service request items" ON service_request_items 
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM service_requests sr 
    WHERE sr.id = service_request_items.service_request_id 
    AND (sr.consultant_id = auth.uid() OR EXISTS (
      SELECT 1 FROM families WHERE families.id = sr.family_id AND families.advisor_id = auth.uid()
    ))
  )
);

CREATE POLICY "Consultants can add items to their requests" ON service_request_items 
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM service_requests sr 
    WHERE sr.id = service_request_items.service_request_id 
    AND sr.consultant_id = auth.uid()
  )
);

-- Service Deliverables policies
DROP POLICY IF EXISTS "Users can view deliverables" ON service_deliverables;
DROP POLICY IF EXISTS "Consultants can add deliverables" ON service_deliverables;
DROP POLICY IF EXISTS "Consultants can update deliverables" ON service_deliverables;
DROP POLICY IF EXISTS "Consultants can delete deliverables" ON service_deliverables;

CREATE POLICY "Users can view deliverables" ON service_deliverables 
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM service_requests sr 
    WHERE sr.id = service_deliverables.service_request_id 
    AND (sr.consultant_id = auth.uid() OR EXISTS (
      SELECT 1 FROM families WHERE families.id = sr.family_id AND families.advisor_id = auth.uid()
    ))
  )
);

CREATE POLICY "Consultants can add deliverables" ON service_deliverables 
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM service_requests sr 
    WHERE sr.id = service_deliverables.service_request_id 
    AND sr.consultant_id = auth.uid()
  )
);

CREATE POLICY "Consultants can update deliverables" ON service_deliverables 
FOR UPDATE USING (
  EXISTS (
    SELECT 1 FROM service_requests sr 
    WHERE sr.id = service_deliverables.service_request_id 
    AND sr.consultant_id = auth.uid()
  )
);

CREATE POLICY "Consultants can delete deliverables" ON service_deliverables 
FOR DELETE USING (
  EXISTS (
    SELECT 1 FROM service_requests sr 
    WHERE sr.id = service_deliverables.service_request_id 
    AND sr.consultant_id = auth.uid()
  )
);

-- Family Advisor Associations policies
DROP POLICY IF EXISTS "Consultants can view their associations" ON family_advisor_associations;
DROP POLICY IF EXISTS "Advisors can view associations for their families" ON family_advisor_associations;
DROP POLICY IF EXISTS "Advisors can manage associations for their families" ON family_advisor_associations;

CREATE POLICY "Consultants can view their associations" ON family_advisor_associations 
FOR SELECT USING (auth.uid() = consultant_id);

CREATE POLICY "Advisors can view associations for their families" ON family_advisor_associations 
FOR SELECT USING (
  EXISTS (SELECT 1 FROM families WHERE families.id = family_advisor_associations.family_id AND families.advisor_id = auth.uid())
);

CREATE POLICY "Advisors can manage associations for their families" ON family_advisor_associations 
FOR ALL USING (
  EXISTS (SELECT 1 FROM families WHERE families.id = family_advisor_associations.family_id AND families.advisor_id = auth.uid())
);

-- ============================================
-- REALTIME
-- ============================================

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE service_requests;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

-- ============================================
-- AUTO-DECLINE / AUTO-CANCEL FUNCTIONS
-- ============================================

-- Function to auto-decline requests where consultant hasn't responded within 48 hours
CREATE OR REPLACE FUNCTION auto_decline_expired_requests()
RETURNS INTEGER AS $$
DECLARE
  affected_count INTEGER;
BEGIN
  UPDATE service_requests
  SET 
    status = 'declined_consultant',
    decline_reason = 'No response within 48 hours (auto-declined)',
    updated_at = NOW()
  WHERE 
    status = 'pending_consultant'
    AND consultant_response_deadline < NOW();
  
  GET DIAGNOSTICS affected_count = ROW_COUNT;
  
  RETURN affected_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to auto-cancel requests where family hasn't approved within 7 days
CREATE OR REPLACE FUNCTION auto_cancel_unapproved_requests()
RETURNS INTEGER AS $$
DECLARE
  affected_count INTEGER;
BEGIN
  UPDATE service_requests
  SET 
    status = 'cancelled',
    decline_reason = 'Family did not approve within 7 days (auto-cancelled)',
    updated_at = NOW()
  WHERE 
    status = 'awaiting_family_approval'
    AND family_approval_deadline IS NOT NULL
    AND family_approval_deadline < NOW();
  
  GET DIAGNOSTICS affected_count = ROW_COUNT;
  
  RETURN affected_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Combined function to run all auto-decline/cancel checks
-- Call this from Supabase cron or Edge Function
CREATE OR REPLACE FUNCTION process_expired_service_requests()
RETURNS TABLE(
  auto_declined INTEGER,
  auto_cancelled INTEGER
) AS $$
DECLARE
  declined_count INTEGER;
  cancelled_count INTEGER;
BEGIN
  SELECT auto_decline_expired_requests() INTO declined_count;
  SELECT auto_cancel_unapproved_requests() INTO cancelled_count;
  
  RETURN QUERY SELECT declined_count, cancelled_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Done!
SELECT 'Service Requests migration completed!' as status;
